name: Deploy Module
on:
  workflow_call:
    inputs:
      target_env:  # 部署目标参数
        required: true
        type: string
        description: "部署环境 (staging 或 production)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ inputs.target_env }}
        run: ./deploy.sh --env ${{ inputs.target_env }}
