name: Pipeline Orchestrator
on:
  workflow_dispatch:
    inputs:
      action_type:
        description: "选择执行的操作类型"
        required: true
        type: choice
        options:
          - build
          - test
          - deploy
      environment:
        description: "目标环境"
        required: true
        type: choice
        options: [dev, staging, prod]
      safety_check:
        description: "确认执行危险操作"
        type: boolean
        default: false

jobs:
  control-center:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Inputs
        run: |
          echo "执行操作: ${{ inputs.action_type }}"
          echo "目标环境: ${{ inputs.environment }}"
          echo "安全确认: ${{ inputs.safety_check }}"

  build-job:
    needs: control-center
    if: ${{ inputs.action_type == 'build' }}
    uses: ./.github/workflows/build.yml@main
    with:
      env: ${{ inputs.environment }}
      node_ver: 18
    secrets: inherit

  test-job:
    needs: control-center
    if: ${{ inputs.action_type == 'test' }}
    uses: ./.github/workflows/test.yml@main
    with:
      test_level: ${{ contains('dev staging', inputs.environment) && 'basic' || 'full' }}

  deploy-job:
    needs: control-center
    if: ${{ inputs.action_type == 'deploy' }}
    uses: ./.github/workflows/deploy.yml@main
    with:
      target_env: ${{ inputs.environment }}
      _force: ${{ inputs.safety_check && inputs.environment == 'prod' }}
