name: Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 设置Docker-buildx环境
      uses: docker/setup-buildx-action@v3

    - name: 登录docker仓库
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com  # 例如: docker.io, gcr.io, quay.io
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

    - name: 构建并推送
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/fage-public/web-study:${{ github.sha }}

    - name: 设置kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.28.2'


  deploy:
    needs: [build]
    runs-on: [self-hosted, linux]
    steps:
    - name: 配置kubeconfig并部署
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig
        chmod 600 kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl set image deployment/web-study-project web-study-project=registry.cn-hangzhou.aliyuncs.com/fage-public/web-study:${{ github.sha }} -n home-web
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

